# Generated by Django 4.2
import uuid
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('city', models.CharField(max_length=120)),
                ('mood', models.CharField(max_length=40)),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('budget_cop', models.PositiveIntegerField()),
                ('group_size', models.PositiveSmallIntegerField()),
                ('transport', models.CharField(max_length=40)),
                ('interests', models.JSONField(default=list)),
                ('raw_places', models.JSONField(default=dict)),
                ('ai_plan_json', models.JSONField(default=dict)),
                ('title', models.CharField(max_length=180)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_saved', models.BooleanField(default=True)),
            ],
            options={'ordering': ['-created_at']},
        ),
        migrations.CreateModel(
            name='PlanStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('block', models.CharField(choices=[('tarde', 'Tarde'), ('noche', 'Noche')], max_length=10)),
                ('order', models.PositiveIntegerField()),
                ('place_name', models.CharField(max_length=180)),
                ('address', models.CharField(blank=True, max_length=220)),
                ('rating', models.FloatField(blank=True, null=True)),
                ('maps_url', models.URLField(blank=True, null=True)),
                ('est_time_minutes', models.PositiveIntegerField(blank=True, null=True)),
                ('est_cost_cop', models.PositiveIntegerField(blank=True, null=True)),
                ('why', models.TextField()),
                ('description', models.TextField()),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='steps', to='core.plan')),
            ],
            options={'ordering': ['block', 'order']},
        ),
    ]
