# Generated by Django 4.2.28 on 2026-02-24 02:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("core", "0002_plan_user_alter_plan_is_saved"),
    ]

    operations = [
        migrations.CreateModel(
            name="FavoritePlan",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("prompt", models.TextField()),
                ("city", models.CharField(max_length=120)),
                ("country", models.CharField(blank=True, max_length=8)),
                ("mood", models.CharField(max_length=40)),
                ("group", models.CharField(blank=True, max_length=80)),
                ("budget_cop", models.PositiveIntegerField(default=0)),
                ("source_payload", models.JSONField(default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="favorite_plans",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="FavoritePlace",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("window_label", models.CharField(max_length=50)),
                ("window_start", models.CharField(blank=True, max_length=10)),
                ("window_end", models.CharField(blank=True, max_length=10)),
                ("name", models.CharField(max_length=180)),
                ("place_id", models.CharField(max_length=200)),
                ("rating", models.FloatField(blank=True, null=True)),
                (
                    "user_ratings_total",
                    models.PositiveIntegerField(blank=True, null=True),
                ),
                ("price_level", models.IntegerField(blank=True, null=True)),
                (
                    "estimated_cost_cop",
                    models.PositiveIntegerField(blank=True, null=True),
                ),
                ("address", models.CharField(blank=True, max_length=255)),
                ("photo_url", models.URLField(blank=True)),
                ("maps_url", models.URLField(blank=True)),
                ("raw_payload", models.JSONField(default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "favorite_plan",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="places",
                        to="core.favoriteplan",
                    ),
                ),
            ],
            options={
                "ordering": ["window_label", "-rating", "name"],
            },
        ),
    ]
