# Generated by ChatGPT
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_favoriteplan_favoriteplace'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.DeleteModel(name='PlanStep'),
        migrations.DeleteModel(name='FavoritePlace'),
        migrations.DeleteModel(name='FavoritePlan'),
        migrations.DeleteModel(name='Plan'),
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=120)),
                ('city', models.CharField(max_length=80)),
                ('city_slug', models.SlugField(max_length=90)),
                ('mood', models.CharField(blank=True, max_length=40)),
                ('group', models.CharField(blank=True, max_length=40)),
                ('budget_cop', models.IntegerField(blank=True, null=True)),
                ('prompt_text', models.TextField()),
                ('plan_json', models.JSONField(default=dict)),
                ('is_public', models.BooleanField(default=False)),
                ('share_code', models.CharField(blank=True, max_length=12, unique=True)),
                ('likes_count', models.IntegerField(default=0)),
                ('saves_count', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plans', to=settings.AUTH_USER_MODEL)),
            ],
            options={'ordering': ['-created_at']},
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username_slug', models.SlugField(max_length=160, unique=True)),
                ('display_name', models.CharField(max_length=60)),
                ('bio', models.TextField(blank=True)),
                ('city_default', models.CharField(blank=True, max_length=80)),
                ('city_slug', models.SlugField(blank=True, max_length=90)),
                ('likes_tags', models.JSONField(blank=True, default=list)),
                ('fears_tags', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PlanItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_label', models.CharField(max_length=20)),
                ('order', models.IntegerField(default=0)),
                ('place_id', models.CharField(max_length=80)),
                ('name', models.CharField(max_length=200)),
                ('rating', models.FloatField(blank=True, null=True)),
                ('user_ratings_total', models.IntegerField(blank=True, null=True)),
                ('price_level', models.IntegerField(blank=True, null=True)),
                ('address', models.CharField(blank=True, max_length=255)),
                ('photo_reference', models.TextField(blank=True)),
                ('photo_url', models.TextField(blank=True)),
                ('maps_url', models.TextField(blank=True)),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='core.plan')),
            ],
            options={'ordering': ['time_label', 'order']},
        ),
        migrations.CreateModel(
            name='PlanLike',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes', to='core.plan')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plan_likes', to=settings.AUTH_USER_MODEL)),
            ],
            options={'constraints': [models.UniqueConstraint(fields=('user', 'plan'), name='unique_plan_like')]},
        ),
        migrations.CreateModel(
            name='PlanSave',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saves', to='core.plan')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plan_saves', to=settings.AUTH_USER_MODEL)),
            ],
            options={'constraints': [models.UniqueConstraint(fields=('user', 'plan'), name='unique_plan_save')]},
        ),
    ]
