# Generated by Django 4.2.28 on 2026-02-24 03:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0005_remove_userprofile_fears_tags_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="about",
            field=models.CharField(blank=True, max_length=160),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="city",
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="country",
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="hobbies_tags",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="instagram",
            field=models.CharField(blank=True, max_length=60),
        ),
    ]
