# Generated by Django 4.2.28 on 2026-02-24 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0007_conversation_message_plancomment_planjoin_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="plan",
            name="city_name",
            field=models.CharField(default="", max_length=80),
        ),
        migrations.AddField(
            model_name="plan",
            name="country_code",
            field=models.CharField(default="CO", max_length=2),
        ),
        migrations.AlterField(
            model_name="plan",
            name="city",
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AlterField(
            model_name="plan",
            name="city_slug",
            field=models.SlugField(blank=True, max_length=90),
        ),
    ]
